version: '3'
services: 
  app:
    build: .
    links: 
      - local-mysql
      - local-redis
    ports:
      - '3000:3000'
  local-mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: asdfg
    # expose ports for test and check
    ports:
      - "3307:3306"
  local-redis:
    image: redis:5
    restart: always
    volumes:
      - ./redis/data:/data
    # expose ports for test and check
    ports:
      - "6279:6379" 
    command: redis-server --appendonly yes